-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'COLLABORATOR_ADDED';
ALTER TYPE "NotificationType" ADD VALUE 'COLLABORATOR_REMOVED';
ALTER TYPE "NotificationType" ADD VALUE 'COLLABORATOR_ROLE_CHANGED';
